### ISSUE TITLE
Реализовать статистику

### ISSUE THREAD

**Issue by pastuhov** [sima-land/api-php-client#10]
общее:
1. общее время работы
2. общее время ожидания
3. кол-во циклов ожидания (сбой в апи)

по каждой сущности:
1. скорость парсинга
2. кол-во

выводить в коносль

**Comment by pahanini** [comment]
Может не в консоль, а просто сделать логгер, уж куда он будет отправлять дело десятое

**Comment by pastuhov** [comment]
я за монолит с остальными частями (так, чтобы нельзя была "забыть" при сборке кода или конфигурации), включение по дефолту
можно логгером, но монолитно
