### ISSUE TITLE
Реализовать отправку статистики

### ISSUE THREAD

**Issue by pastuhov** [sima-land/api-php-client#11]
Вот эту статистику #10 отправлять по REST Разработчику в целях контроля качества.

**Comment by jetexe** [comment]
ни в коем случае

**Comment by pastuhov** [comment]
а что смущает?

**Comment by jetexe** [comment]
@pastuhov как минимум то, что с моего сервера будут уходить данные в неизвестном направлении, а патчить это при каждом обновлении не хочется
 Сама статистика идея не плохая. Не знаю, проведите "опрос". 
Лично меня смущает сбор какой-либо статистики третьими лицами на продакшн серверах

**Comment by pastuhov** [comment]
Пока это лишь идея. Статистика будет уходить только в известном направлении, на .sima-land.ru, также будет опция, которую можно будет выключить, но по умолчанию она будет включена.
