### ISSUE TITLE
В readme описать не только quick start, но и full-featured example

### ISSUE THREAD

**Issue by pastuhov** [sima-land/api-php-client#16]
текущий пример переименовать в Быстрый старт, добавить еще один - full-featured (со всеми фишками, основными сущностями, готово к использованию, как по-русски не знаю)

**Comment by Belohalatny** [comment]
`$catParams = [

    'with_adult'    => '1',
    'is_not_empty'  => '1',
    'level'         => '1',
];

// добавляем список категорий
$categoryStorage = new \SimaLand\API\Parser\Csv(['filename' => '/home/.../public_html/category.csv']);
$categoryList = new \SimaLand\API\Entities\CategoryList($client, $catParams);
$parser->addEntity($categoryList, $categoryStorage);

$parser->run();`

Не применяются фильтры, выбираются все равно все категории.

**Comment by pahanini** [comment]
@Belohalatny лучше бы создать отдельный issue

**Comment by EvgenyGavrilov** [comment]
В `CategoryList` надо передать Ваши фильтры в параметр `getParams`
```php
$categoryList = new \SimaLand\API\Entities\CategoryList($client, ['getParams' => $catParams]);
```

**Comment by Belohalatny** [comment]
Спасибо, вынесите в примеры.

**Comment by pahanini** [comment]
В документацию добавить описание того, как получать URL фотографий
