### ISSUE TITLE
Команды

### ISSUE THREAD

**Issue by Ruslan-Promo** [sima-land/api-php-client#17]
Здравствуйте! Выполнил установку клиента через команду composer require "sima-land/api-php-client", установка прошла успешна, но далее в консоли не работают команды, к примеру:
 curl -i -H "Accept:application/json" "https://www.sima-land.ru/api/v3/item/"
Ошибка:
Invoke-WebRequest : Missing an argument for parameter 'InFile'. Specify a parameter of type 'System.String' and try again
At line:1 char:6
+ curl -i -H "Accept:application/json" "https://www.sima-land.ru/api/v3/item/"
+      ~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-WebRequest], ParameterBindingException
    + FullyQualifiedErrorId : MissingArgument,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

В чем проблема и как решить её?
P.s. OS Windows Server 2012 R2, WampServer

**Comment by EvgenyGavrilov** [comment]
Не совсем понятно зачем здесь команда curl, библиотека с ней не работает.
Эта библиотека позволит вам делать GET запросы без надобности формирование HTTP заголовков. Достаточно создать небольшой скрипт и сохранить результат выполнения GET запроса.
Документация и пример работы API клиента по этой [ссылке](https://github.com/sima-land/api-php-client/blob/master/doc/client.md)
Так же есть парсер, которая позволит вам скачать каталог по API [https://github.com/sima-land/api-php-client/blob/master/doc/parser.md](https://github.com/sima-land/api-php-client/blob/master/doc/parser.md)

**Comment by pahanini** [comment]
К сожалению, работа на платформе windows не гарантируется. Попробуйте virtualbox или аналог для виртуализации, там установите, к примеру, ubuntu
