### ISSUE TITLE
Не определяет класс

### ISSUE THREAD

**Issue by Ruslan-Promo** [sima-land/api-php-client#18]
Здравствуйте! Возникла следующая проблема 
![1909](https://cloud.githubusercontent.com/assets/22237541/18629411/482e017e-7e76-11e6-82c7-e18179f991f2.jpg)

**Comment by pahanini** [comment]
Дайте пожалуйста ссылку на код testfile.php, скорее всего вы не подключили загрузчик в файл. Попробуйте добавить в ваш файл следующий код:
```php
$loader = require_once __DIR__.'/vendor/autoload.php';
```

**Comment by Ruslan-Promo** [comment]
Благодарю, Вы были правы, заработало)

**Comment by pahanini** [comment]
Пожулайста
