### ISSUE TITLE
Как указать желаемый размер изображений товара?

### ISSUE THREAD

**Issue by Ruslan-Promo** [sima-land/api-php-client#20]
Здравствуйте, а при парсинге у товаров картинки малого размера, есть ли возможность получать их большего размера? Хотя бы оригинального с карточки товара.

**Comment by pastuhov** [comment]
Пожалуйста, для "...смещаются в другие столбцы.." создайте отдельный issue

**Comment by pahanini** [comment]
Создам отдельную задачу на вывод списка фото у товара

**Comment by pahanini** [comment]
https://github.com/sima-land/api-php-client/blob/master/doc/faq.md
