### ISSUE TITLE
Смещение значений в таблице товаров

### ISSUE THREAD

**Issue by Ruslan-Promo** [sima-land/api-php-client#21]
Есть проблемы при парсинге, некоторые значения товаров, к примеру ид категории, смещаются в другие столбцы, в результате все значения просто смещаются и не соответствуют столбцам

**Comment by EvgenyGavrilov** [comment]
Можете привести примеры товаров у которых смещаются колонки

**Comment by Ruslan-Promo** [comment]
Вот укороченный файл csv


[http://dropmefiles.com/acj9Y](url)

**Comment by EvgenyGavrilov** [comment]
Ошибка исправлена.

**Comment by Ruslan-Promo** [comment]
К сожалению, не у всех товаров исправлено, есть еще у кого смещаются значения
[http://dropmefiles.com/6xbfg](url)

**Comment by EvgenyGavrilov** [comment]
Попробуйте обновить код и заново запустить парсер.

**Comment by Ruslan-Promo** [comment]
Обновление не помогло, хотя у большинства товаров исправлены
[http://dropmefiles.com/Lu5ng](url)
