### ISSUE TITLE
Вопрос по подключению

### ISSUE THREAD

**Issue by slavasevas** [sima-land/api-php-client#24]
Здравствуйте, как сайт подключить к каталогам через API ? Спасибо,

**Comment by njspok** [comment]
Уточните ваш вопрос, пожалуйста. Наша библиотека предназначена для того, чтобы вы могли получать наш каталог и сохранять его на своей стороне тем способом, который Вам предпочтителен.

**Comment by slavasevas** [comment]
Хорошо, а где должны размещаться файлы? 
Спасибо


>Понедельник,  3 октября 2016, 9:33 +04:00 от Hamov Oleg <notifications@github.com>:
>
>Уточните ваш вопрос, пожалуйста. Наша библиотека предназначена для того, чтобы вы могли получать наш каталог и сохранять его на своей стороне тем способом, который Вам предпочтителен.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


С Уважением,
Чалов Вячеслав,

тел. 8 978 09 16 718
тел. 8 978 09 16 719

http://ravechnost.ru - Студия Чаловых "Вечность"
http://wlcat.ru    - Питомник элитных кошек "Wild Russia"

https://vk.com/slava_ravechnost
slava_ravechnost@mail.ru

**Comment by pahanini** [comment]
Пожалуйста напишите:

1) какое ПО для интернет магазина вы используете 
2) как вы пытались подключить парсер и какие ошибки при этом получили?

"Хорошо, а где должны размещаться файлы?" - при использовании [composer](https://getcomposer.org/) файлы будут располагаться в папке vendor

Вот тут есть пример готового парсера [parser_example.php](https://github.com/sima-land/api-php-client/blob/master/parser_example.php)

**Comment by slavasevas** [comment]
1. Мы сделали интернет магазин на wordpress 
2. мы еще пытаемся подключиться.

Первый раз с этим сталкиваемся, но хотим разобраться и настроить каталоги на свой интернет магазин. Сайт делали сами.



>Понедельник,  3 октября 2016, 11:55 +04:00 от Pavel Tetyaev <notifications@github.com>:
>
>Пожалуйста напишите:
>1) какое ПО для интернет магазина вы используете 
>2) как вы пытались подключить парсер и какие ошибки при этом получили?
>"Хорошо, а где должны размещаться файлы?" - при использовании  composer файлы будут располагаться в папке vendor
>Вот тут есть пример готового парсера  parser_example.php
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


С Уважением,
Чалов Вячеслав,

тел. 8 978 09 16 718
тел. 8 978 09 16 719

http://ravechnost.ru - Студия Чаловых "Вечность"
http://wlcat.ru    - Питомник элитных кошек "Wild Russia"

https://vk.com/slava_ravechnost
slava_ravechnost@mail.ru

**Comment by pahanini** [comment]
Вы можете взять за образец пример [парсера](https://github.com/sima-land/api-php-client/blob/master/parser_example.php) и в указанных местах, например для [категорий](https://github.com/sima-land/api-php-client/blob/master/parser_example.php#L92), разместить код который будет записывать данные в вашу БД. 

Конкретная реализация зависит от архитектуры вашей БД.

**Comment by slavasevas** [comment]
Хорошо, а какой код нужно вписывать и куда поместить файл парсера, в корень сайта или нужно создать отдельную папку?

>Понедельник,  3 октября 2016, 12:52 +04:00 от Pavel Tetyaev <notifications@github.com>:
>
>Вы можете взять за образец пример  парсера и в указанных местах, например для  категорий , разместить код который будет записывать данные в вашу БД. 
>Конкретная реализация зависит от архитектуры вашей БД.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


С Уважением,
Чалов Вячеслав,

тел. 8 978 09 16 718
тел. 8 978 09 16 719

http://ravechnost.ru - Студия Чаловых "Вечность"
http://wlcat.ru    - Питомник элитных кошек "Wild Russia"

https://vk.com/slava_ravechnost
slava_ravechnost@mail.ru

**Comment by pahanini** [comment]
Конкретная реализация и расположение файла зависит от архитектуры вашей базы, ПО итд.  Обратитесь к разработчику вашего сайта.

**Comment by slavasevas** [comment]
Да, мы сами делали интернет магазин. Попробуем разобраться.

>Понедельник,  3 октября 2016, 13:15 +04:00 от Pavel Tetyaev <notifications@github.com>:
>
>Конкретная реализация и расположение файла зависит от архитектуры вашей базы, ПО итд.  Обратитесь к разработчику вашего сайта. 
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


С Уважением,
Чалов Вячеслав,

тел. 8 978 09 16 718
тел. 8 978 09 16 719

http://ravechnost.ru - Студия Чаловых "Вечность"
http://wlcat.ru    - Питомник элитных кошек "Wild Russia"

https://vk.com/slava_ravechnost
slava_ravechnost@mail.ru
