### ISSUE TITLE
при выгрузке товаров в csv поля съезжают

### ISSUE THREAD

**Issue by VRn00b** [sima-land/api-php-client#25]
пример:

> id=>1404354
> sid=>1382535
> uid=>d49acaa4-f55f-11e5-80c0-00155d65b108
> name=>"Ежедневникъ" 280 стр (красный) 14,5 х 21 см
> ...
> photos=>{"id":356,"name":"Индия","full_name":"Республика Индия","alpha2":"IN"}
> country=>
> offer=>0
> discountPercent=>https://st-sima.r.worldssl.net/items/1404354/0/140.jpg
> img=>
> hasGift=>
> hasGiftAssignee=>1
> isNovelty=>/1382535/ezhednevnik-280-str-krasnyy-14-5-h-21-cm/
> itemUrl=>

**Comment by VRn00b** [comment]
**читаю так:**
> if (($handle = fopen("/home/bitrix/www/local/sima/item.csv", "r")) !== FALSE) {
> 	while (($data = fgetcsv($handle, 2000, ";",'"')) !== FALSE) {
>     	$counts[count($data)]++;
>     }
>     print_r($counts);
> }

**результат:**

> Array
> (
>     [137] => 56469
>     [136] => 88626
>     [134] => 5
>     [4] => 8
>     [129] => 8
>     [8] => 15
>     [132] => 2
>     [5] => 2
>     [133] => 4
>     [1] => 4
>     [130] => 7
>     [3] => 3
>     [128] => 1
>     [9] => 1
>     [127] => 2
>     [10] => 2
>     [121] => 1
>     [16] => 1
>     [135] => 3
>     [126] => 11
>     [12] => 12
>     [122] => 1
>     [15] => 1
>     [2] => 1
>     [125] => 1
> )
>

**Comment by VRn00b** [comment]
выяснил что проблема в параметре balance, он не всегда указывается в джсоне, а csv вместо него вставляет последующий вместо пустого и сбивается

**Comment by VRn00b** [comment]
**временное решение для себя Parser/Csv.php:**
>     public function save(Record $record)
>     {
>         $this->open();
>         $item = $record->data;
>         foreach ($item as &$value) {
>             if (is_array($value)) {
>                 $value = json_encode($value, JSON_UNESCAPED_UNICODE);
>             }
>         }
>         if (!$this->isSaveHeader) {
>             $keys = array_keys($item);
>             fputcsv($this->fileHandler, $keys, $this->delimiter, $this->enclosure);
>             $this->isSaveHeader = true;
>             $this->balance = array_search('balance', $keys);//запишем индекс
>         }
>         if (!isset($item['balance'])) {//bugfix
>         	$item = array_slice($item, 0, $this->balance, true) +
> 			    array("balance" => 0) +
> 			    array_slice($item, $this->balance, count($item) - 1, true) ;
>         }
>         fputcsv($this->fileHandler, $item, $this->delimiter, $this->enclosure);
>     }

**Comment by pahanini** [comment]
Лучше сразу сохраняйте данные в вашу БД, а не в csv-файл.

Сохранение в [csv-файл](https://github.com/sima-land/api-php-client/blob/master/src/Parser/Csv.php) наверное не самое удачное решение, так как перечень полей, возвращаемых API, может меняться. Скоро выпустим исправление.

**Comment by VRn00b** [comment]
поэтому я сначала записываю индексы в массив

> $ind = array_flip(fgetcsv($handle, 2000, ";"));//запишем индексы

и обращаюсь к ним по именам:

>  echo $data[$ind['name']];

**Comment by pahanini** [comment]
https://github.com/sima-land/api-php-client/pull/26
