### ISSUE TITLE
Интерфейс API

### ISSUE THREAD

**Issue by DVS1977** [sima-land/api-php-client#28]
Прошу мне помочь, т.к. я не совсем программист, но освоить могу хоть что.
Подскажите с чего нужно начать, чтобы настроить работу интерфейса API на моем сайте?
1. Как правильно сформировать запрос на определенные категории товаров?
2. Куда нужно писать запрос?
3. Каким должен быть ответ на запрос?
4. Что делать с ответом на запрос?

**Comment by njspok** [comment]
Изучите документацию и демонстрационный пример этого проекта.

**Comment by pahanini** [comment]
В любом случае вам понадобится помощь программиста, т.к. парсер это инструмент, а не готовое решение.

**Comment by DVS1977** [comment]
Где его найти? У меня удаленный район - это раз. Во вторых те программисты которые ищут работу в центре города представления не имеют об этом интерфейсе. И третье есть множество роликов в инете по поводу настройки API таких сайтов как ВК, одноклассники и многие другие, там это все происходит в несколько шагов. Неужели нет в СимаЛенде подобных инструкций видео или письменных. В общем нужна помощь, что делать? Готов освоить первые попытки, скажите куда тыкать. Спасибо.

**Comment by pahanini** [comment]
Обратитесь за консультацией в отдел поддержки бизнеса компании, заявку можно оставить здесь https://www.sima-land.ru/info/shop/
