### ISSUE TITLE
Какой параметр для изображений?

### ISSUE THREAD

**Issue by Ruslan-Promo** [sima-land/api-php-client#29]
Здравствуйте! В faq не ясно, как получать фотографии нужного размера через парсер, поэтому возникает вопрос, какой параметр (getParams) нужно передавать для получения необходимого размера фотографии без водяного знака?

**Comment by pahanini** [comment]
Фотографии через парсер получить нельзя. Можно получить URL фото нужного формата и в дальнейшем скачать её. Как сформировать URL описано в FAQ.

**Comment by Ruslan-Promo** [comment]
Я правильно понимаю, нельзя изменить ссылки изображений, которые в таблицу парсером заносятся?
К примеру, вместо такой фотки https://st-sima.r.worldssl.net/items/785/0/140.jpg, чтобы формировалось https://st-sima.r.worldssl.net/items/785/0/700-nw.jpg

**Comment by EvgenyGavrilov** [comment]
Да. Поле `img` сущности `item` содержит только первую фотографию товара размером 140х140. Поле `photos` содержит список базовых URL для получения фотографий. К базовым URL достаточно добавить имя файла желаемого размера.
