### ISSUE TITLE
Получение товаров в наличии

### ISSUE THREAD

**Issue by Ruslan-Promo** [sima-land/api-php-client#30]
Здравствуйте! А можно ли через парсер получать только товары, которые в наличии?

**Comment by pahanini** [comment]
Перечень товаров которые возвращает парсер зависит от URL который вы ему передали. Смотрите параметры URL здесь https://www.sima-land.ru/api/v3/help/#Товар раздел "параметры запроса"

**Comment by GTAlex** [comment]
Можно как то узнать о параметрах запроса, идентичных тем, что выводятся на сайте?

Например, в категории 
https://www.sima-land.ru/igrushki/igrushki-dlya-malchikov/roboty-transformery/transformery/ 
на сайте отображается 370 товаров

А если же делать запрос парсером по categoty_id = 1763 
в файле создаётся 1496 строк сущностей Товар
