### ISSUE TITLE
Не полностью выгружаются товары

### ISSUE THREAD

**Issue by Ruslan-Promo** [sima-land/api-php-client#33]
Здравствуйте! Использую такой код для парсинга, но он выгружает не все товары, которые в наличии, а только около 257 тысяч вместо 484 тысяч
$categoryStorage = new \SimaLand\API\Parser\Csv(['filename'=>$path_category]);
$categoryList = new \SimaLand\API\Entities\CategoryList($client,['getParams'=>['with_adult'=>1]]);
$parser->addEntity($categoryList, $categoryStorage);

$itemStorage = new \SimaLand\API\Parser\Csv(['filename'=>$path_item]);
$itemList = new \SimaLand\API\Entities\ItemList($client,['getParams'=>['with_adult'=>1, 'has_balance'=>1, 'has_photo'=>1, 'is_gift'=>0]]);
$parser->addEntity($itemList,$itemStorage);

$parser->reset();
$parser->run();

**Comment by pahanini** [comment]
Обновите парсер

**Comment by Ruslan-Promo** [comment]
После обновления возникла ошибка
![image](https://cloud.githubusercontent.com/assets/22237541/19917250/e55eb728-a0da-11e6-9c73-f4c98e9ab007.png)

**Comment by EvgenyGavrilov** [comment]
Сейчас нет сохранение в csv файл, т. к. API может возвращать разный набор полей, как следствие этого может быть сдвиг колонок в файле. Сейчас идет сохранение в json формате. Каждая строка это запись сущности в json формате.

**Comment by Ruslan-Promo** [comment]
А когда можно ожидать появление возможности сохранения в csv?

**Comment by EvgenyGavrilov** [comment]
Такой возможности не будет.
