### ISSUE TITLE
Не получается получить заголовок Etag в запросах.

### ISSUE THREAD

**Issue by panda-madness** [sima-land/api-php-client#35]
Ни через curl, ни через библиотеку никак не могу получить Etag в хедерах.

GET https://www.sima-land.ru/api/v3/item/

Хедеры ответа

```
Content-Encoding: gzip
Content-Type: application/json; charset=UTF-8
Date: Tue, 01 Nov 2016 05:51:10 GMT
Link: <https://www.sima-land.ru/api/v3/item/?page=1>; rel=self, <https://www.sima-land.ru/api/v3/item/?page=2>; rel=next, <https://www.sima-land.ru/api/v3/item/?page=25484>; rel=last
Server: nginx
Set-Cookie: userSettings=098f88b4af38509ca4193fce26dc09c613d23ee8422d3b7cfa3e5eb678cc7e5ba%3A2%3A%7Bi%3A0%3Bs%3A12%3A%22userSettings%22%3Bi%3A1%3Bs%3A42%3A%22%7B%22sort%22%3A%22%22%2C%22per_page%22%3A20%2C%22currency%22%3A%22RUB%22%7D%22%3B%7D; path=/; HttpOnly
Transfer-Encoding: chunked
X-Pagination-Current-Page: 1
X-Pagination-Page-Count: 25484
X-Pagination-Per-Page: 50
X-Pagination-Total-Count: 1274191
access-control-allow-credentials: true
```

**Comment by pahanini** [comment]
Etag не отдается сервером

**Comment by panda-madness** [comment]
https://www.sima-land.ru/api/v3/help/#%D0%9A%D1%8D%D1%88%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5
Доки вводят в заблуждение :(
Как тогда правильно имплементировать обновление локальной базы с вашего АПИ? Сейчас приходиться заного тянуть всю базу, что занимает много времени.

**Comment by pahanini** [comment]
Item и Category не возвращают etag. Мы исправим документацию. База меняется очень интенсивно, поэтому лучшее решение на сегодняшний это затягивать всю базу, например, раз в сутки.

**Comment by panda-madness** [comment]
Ясно, большое спасибо за разъяснение!
