### ISSUE TITLE
Нету примера использования поискового запроса в товарах.

### ISSUE THREAD

**Issue by panda-madness** [sima-land/api-php-client#36]
В документации к сущности Товары одним из полей для получения списка является параметр q - поисковый запрос. Как им пользоваться? Что он вообще делает?

**Comment by EvgenyGavrilov** [comment]
Параметр q осуществляет поиск товаров по строке.
Его можно использовать следующим образом
```php
$itemList = new \SimaLand\API\Entities\ItemList(
    $client,
    [
        'getParams' => ['q' => 'игры']
    ]
);
```

**Comment by panda-madness** [comment]
Спасибо! Я так понимаю, ищет как по имени так и по категориям?

**Comment by EvgenyGavrilov** [comment]
Идет полнотекстовый поиск, по нескольким критериям куда входят и наименование товара категории, торговой марки и т. п.
