### ISSUE TITLE
С чего начать?

### ISSUE THREAD

**Issue by MetallFlame** [sima-land/api-php-client#37]
Пытаюсь разобраться, но с чего начать? Что конкретно нужно установить, как запустить и куда писать код?

**Comment by pahanini** [comment]
Начните с прочтения документации. [Здесь](https://github.com/sima-land/api-php-client/blob/master/parser_example.php) есть пример приложения с большим количеством комментариев.

Постарайтесь задавать конкретные вопросы содержащие описание того, что вы делали, что пошло не так, какие ошибки получены.

**Comment by MetallFlame** [comment]
Конкретно вопрос звучит так: Есть необходимость выгрузки каталога. Как я понимаю, выгрузка делается в файл. Так вот, установили php, composer. Куда вводить код?
Конкретно этот код:     composer require "sima-land/api-php-client": "~3"

**Comment by pahanini** [comment]
В примере выгрузка делается в файл. Данный код нужно вводить в консоли, а лучше добавить парсер в перечень зависимостей вашего проекта,  прочитайте документацию по composer.

Какова цель выгрузки каталога? Если интеграция с интернет магазином, то помимо выгрузки придется решить много других проблем и если Вы не разработчик, то необходимо будет помощь программиста.

Если просто нужно просто выгрузить файл с каталогом, то можно воспользоваться [yml](https://www.sima-land.ru/yml/category/) файлами.

**Comment by MetallFlame** [comment]
Нужно выгрузить каталог и загрузить его на сайт на wordpress

**Comment by pahanini** [comment]
Попробуйте это решение
https://ru.wordpress.org/plugins/wp-shop-yml-parser/

**Comment by MetallFlame** [comment]
Всё отлично, только картинок нет. Спасибо за помощь! А что с картинками можно придумать?

**Comment by MetallFlame** [comment]
С картинками тоже разобрался!! Спасибо за помощь)

**Comment by pahanini** [comment]
пожалуйста
