### ISSUE TITLE
Реализовать возможность загрузки всех товаров в категории с потомками или без них

### ISSUE THREAD

**Issue by covox** [sima-land/api-php-client#41]
Сейчас вообще не понятно как сделать выгрузку всех товаров из определенной категории.
В api v3 это можно, но там нет параметра, чтобы не загружать потомков. Для нормальной работы нужны оба варианта загрузки.

**Comment by pastuhov** [comment]
Товары находятся только в категориях с `is_leaf: 1`. Товары могут находиться только в конечных категориях, нет смысла в параметре "не загружать потомков".
