### ISSUE TITLE
Отдавать дерево категорий в nested set

### ISSUE THREAD

**Issue by covox** [sima-land/api-php-client#42]
При загрузке полного дерева категорий, вы отдаете только parent_id, и поэтому дерево приходится строить самостоятельно. При вашем гигантском количестве категорий, серверы клиентов загибаются от нагрузки во время пересчета. 

Просьба отдать все необходимые ключи для nested set (left, right, deep, parent).

**Comment by pastuhov** [comment]
Мы не используем `nested set`. Для пересчетов используйте поле `path`.

```
path	string	Последовательность идентификаторов категорий, разделённых точкой, представляющая путь до заданной категории от корня дерева категорий
```
