### ISSUE TITLE
Получение обновлений

### ISSUE THREAD

**Issue by jetexe** [sima-land/api-php-client#43]
У вашего магазина очень много товаров. Обрабатывать полный список "на лету" нет возможности. Подскажите как можно получить список лишь изменившихся и добавленных товаров и категорий?

**Comment by pastuhov** [comment]
В базе происходит часто и много имений, уже через час вся база может быть изменена.
В начале следующей недели планируем дать возможность максимально быстрой загрузки баланса и цены через api v5 https://www.sima-land.ru/api/v5/help, это api быстрее api v3.

**Comment by jetexe** [comment]
Спасибо за ответ. Придется дёргать метод списка товаров? это всё равно долго и генерирует десятки гигабайт трафика

**Comment by pastuhov** [comment]
Фильтрацию по дате создания продумываем, сроки пока не скажу

**Comment by pastuhov** [comment]
Теперь на api v5 возможны запросы вида `https://www.sima-land.ru/api/v5/item?p=1&short=true` (требуется получение токена, см. документацию)
Возможный ответ:
```
[
  {
    "balance": "0",
    "id": 649,
    "price": 7.38,
    "sid": 652
  },
  {
    "balance": "0",
    "id": 686,
    "price": 10.55,
    "sid": 683
  },
```
В ответе только 4 поля, трафика меньше. Подробнее тут https://www.sima-land.ru/api/v5/help#/Товары

**Comment by pastuhov** [comment]
Для максимально быстрой загрузки баланса теперь можно воспользоваться запросом вида `https://www.sima-land.ru/api/v5/item?p=1&view=brief` (требуется токен, см. документацию).
Дает ответ вида:
```
[
  {
    "balance": "0",
    "id": 550,
    "price": 21.09,
    "sid": 551
  },
  {
    "balance": "0",
    "id": 649,
    "price": 7.38,
    "sid": 652
  },
```
Подробнее https://www.sima-land.ru/api/v5/help#/Товары
