### ISSUE TITLE
Фильтр по партии

### ISSUE THREAD

**Issue by GTAlex** [sima-land/api-php-client#47]
Здравствуйте!
Подскажите как отфильтровать товары по минимальной партии?
Например, такой фильтр
https://www.sima-land.ru/igrushki/igrushki-dlya-malchikov/roboty-transformery/?per-page=100&f={%22agg_min_qty%22:[%221_91%22,%222_82%22]}

**Comment by EvgenyGavrilov** [comment]
Такой возможности нет. Вы можете загрузить весь каталог и организовать фильтрацию у себя.
