### ISSUE TITLE
Параметры по умолчанию 

### ISSUE THREAD

**Issue by GTAlex** [sima-land/api-php-client#49]
Можно как то узнать о параметрах запроса, идентичных тем, что выводятся на сайте?

Например, в категории
https://www.sima-land.ru/igrushki/igrushki-dlya-malchikov/roboty-transformery/transformery/
на сайте отображается 370 товаров

А если же делать запрос парсером по categoty_id = 1763
в файле создаётся 1496 строк сущностей Товар

**Comment by EvgenyGavrilov** [comment]
Такой возможности нет. Вы можете сами задавать параметры (https://github.com/sima-land/api-php-client/blob/master/parser_example.php#L59).
Все параметры описаны здесь https://www.sima-land.ru/api/v3/help/
