### ISSUE TITLE
Тесты

### ISSUE THREAD

**Issue by GTAlex** [sima-land/api-php-client#50]
в папке /tests/ реализованы тестовые скрипты
как из запускать ?
никакой документации не нашел :(

например, при запуске ItemListTest.php  пишет 
Fatal error: Class 'SimaLand\API\Tests\BaseCase' not found in /..../tests/ItemListTest.php on line 10

**Comment by EvgenyGavrilov** [comment]
В документации описаны как запускать тесты https://github.com/sima-land/api-php-client#Тесты
Запустить определенный тест вы можете командой
```sh
php ./vendor/bin/phpunit tests/ItemListTest.php
```
