### ISSUE TITLE
Не корректно работают списковые API запросы к сущности "Связь атрибута с товаром" - не учитываются входные параметры

### ISSUE THREAD

**Issue by GTAlex** [sima-land/api-php-client#51]
мне нужно получить список свойств товара
делаю запрос по item_id
https://www.sima-land.ru/api/v3/attr-item/?item_id=1255080
получаю первую партию ВСЕГО! списка, со значениями к item_id=1255080 никак не относящимися!

даже по id не пашет
https://www.sima-land.ru/api/v3/attr-item/?id=36450,36451

**Comment by EvgenyGavrilov** [comment]
Для сущности https://www.sima-land.ru/api/v3/attr-item/ не реализована выборка по `item_id`
Для получения дополнительных полей сущности `item` следует использовать GET параметр expand
`Пример`: https://www.sima-land.ru/api/v3/item/1255080/?expand=attrs

Документация: https://www.sima-land.ru/api/v3/help/#Товар
