### ISSUE TITLE
Вопрос по версиям АПИ

### ISSUE THREAD

**Issue by Major666RUS** [sima-land/api-php-client#52]
Здравствуйте.
Сейчас интеграция реализована на api v2, получили письмо насчет его закрытия.

Что лучше, перейти на v3 или сразу на v5?

И вопрос по v5:
Насколько я понял, там нет возможности получать рубрики первого уровня, подрубрики рубрик, а только весь список.
Предполагается, что сначала выгружается весь список рубрик и товаров, а потом локально формируется дерево каталога (по path)?
И как предполагается определять последний Номер страницы (p) - увеличивать до тех пор пока не вернется ошибка?

**Comment by jetexe** [comment]
> И как предполагается определять последний Номер страницы (p) - увеличивать до тех пор пока не вернется ошибка?
Пока количество результатов = max count

**Comment by pahanini** [comment]
Для выкачивания каталога нужно использовать версию 5. На остальные вопросы @jetexe абсолютно точно ответил.
