### ISSUE TITLE
Ограничения API v5

### ISSUE THREAD

**Issue by jetexe** [sima-land/api-php-client#53]
Приветствую. Методом научного тыка установил, что https://www.sima-land.ru/api/v5/item?p=n&view=brief. Принимает 249 запросов в секунду, потом выбивает в 403. Сколько нужно ждать пока не ясно (чаще всего 5 секунд достаточно, но иногда приходится ждать больше). В документации по v5 нет ни строчки об этом.
Подскажите какие лимиты у v5 и добавьте это в хелп

**Comment by jetexe** [comment]
Есть ли какие-либо новости?

**Comment by pastuhov** [comment]
Вот-вот мы увеличим лимиты и укажем всю информацию в документации. Здесь так же отпишемся по готовности.

**Comment by pastuhov** [comment]
На текущий момент установлены следующие ограничения:
- Не более 30 запросов в секунду
- Не более 5 запросов с ошибками секунду
(в документации сейчас указаны другие, старые, после обкатки новых, обновим)

**Comment by EvgenyGavrilov** [comment]
+ 300 запросов в 10 секунд

**Comment by MrSmitix** [comment]
Вечер добрый. 8 лет прошло, поменялось что? По моим ощущениям очень даже. 80.000 страниц с товарами парсер обрабатывает минут за 20-25. Получается в районе 50-60/сек. Хотелось бы узнать точные и актуальные данные, если можно
