### ISSUE TITLE
API v5 page 15057 (Или где-то рядом)

### ISSUE THREAD

**Issue by jetexe** [sima-land/api-php-client#54]
[{"balance":"0","id":1623644,"price":155.4,"sid":1994203}
,{"balance":"0","id":1623667,"price":550.8,"sid":1995517}
,{"balance":"0","id":1623624,"price":418.48,"sid":1994634}
,{"balance":"0","id":1623623,"price":313.14,"sid":1993349}
,{"balance":"0","id":1623668,"price":212.16,"sid":1993356}
,{"balance":"0","id":1623614,"price":244.94,"sid":1993758}
,{"balance":"0","id":1623625,"price":244.94,"sid":1993760}
,{"balance":"0","id":1623701,"price":244.94,"sid":1993774}
,{"balance":"0","id":1623652,"price":212.16,"sid":1993353}
,{"balance":"0","id":1623693,"price":184.26,"sid":1994212}
,{"balance":"0","id":1623680,"price":155.4,"sid":1994210}
,{"balance":"0","id":1623676,"price":244.94,"sid":1993769}
,{"balance":"0","id":1623685,"price":184.26,"sid":1994211}
,{"balance":"0","id":1623633,"price":391.68,"sid":1995511}
,{"balance":"0","id":1623636,"price":418.48,"sid":1994636}
,{"balance":"0","id":1623612,"price":418.48,"sid":1994632}
,{"balance":"0","id":1623695,"price":550.8,"sid":1995523}
,{"balance":"0","id":1623709,"price":212.16,"sid":1993365}
,{"balance":"0","id":1623688,"price":2.5761914952e+09,"sid":1993360}
,{"balance":"0","id":1623656,"price":244.94,"sid":1993765}
,{"balance":"0","id":1623655,"price":155.4,"sid":1994205}
,{"balance":"0","id":1623702,"price":143.19,"sid":1994648}
,{"balance":"0","id":1623705,"price":550.8,"sid":1995525}
,{"balance":"0","id":1623654,"price":134.31,"sid":1995073}
,{"balance":"0","id":1623673,"price":212.16,"sid":1993357}
,{"balance":"0","id":1623615,"price":391.68,"sid":1995508}
,{"balance":"0","id":1623648,"price":134.31,"sid":1995072}
,{"balance":"0","id":1623611,"price":313.14,"sid":1993347}
,{"balance":"0","id":1623700,"price":550.8,"sid":1995524}
,{"balance":"0","id":1623639,"price":155.4,"sid":1994202}
,{"balance":"0","id":1623675,"price":418.48,"sid":1994643}
,{"balance":"0","id":1623640,"price":391.68,"sid":1995512}
,{"balance":"0","id":1623698,"price":184.26,"sid":1994213}
,{"balance":"0","id":1623691,"price":550.8,"sid":1995522}
,{"balance":"0","id":1623642,"price":134.31,"sid":1995071}
,{"balance":"0","id":1623637,"price":313.14,"sid":1993351}
,{"balance":"0","id":1623610,"price":155.4,"sid":1994197}
,{"balance":"0","id":1623690,"price":2.5761914952e+09,"sid":1993361}
,{"balance":"0","id":1623650,"price":391.68,"sid":1995514}
,{"balance":"0","id":1623620,"price":391.68,"sid":1995509}
,{"balance":"0","id":1623626,"price":134.31,"sid":1995068}
,{"balance":"0","id":1623618,"price":134.31,"sid":1995067}
,{"balance":"0","id":1623708,"price":251.84,"sid":1993775}
,{"balance":"0","id":1623671,"price":550.8,"sid":1995518}
,{"balance":"0","id":1623684,"price":468.43,"sid":1994645}
,{"balance":"0","id":1623661,"price":244.94,"sid":1993766}
,{"balance":"0","id":1623689,"price":143.19,"sid":1994646}
,{"balance":"0","id":1623687,"price":244.94,"sid":1993771}
,{"balance":"0","id":1623628,"price":155.4,"sid":1994200}
,{"balance":"0","id":1623678,"price":212.16,"sid":1993358}
,{"balance":"0","id":1623631,"price":418.48,"sid":1994635}
,{"balance":"0","id":1623696,"price":143.19,"sid":1994647}
,{"balance":"0","id":1623641,"price":418.48,"sid":1994637}
,{"balance":"0","id":1623632,"price":134.31,"sid":1995069}
,{"balance":"0","id":1623706,"price":143.19,"sid":1994649}
,{"balance":"0","id":1623666,"price":244.94,"sid":1993767}
,{"balance":"0","id":1623657,"price":391.68,"sid":1995515}
,{"balance":"0","id":1623682,"price":550.8,"sid":1995520}
,{"balance":"0","id":1623660,"price":155.4,"sid":1994206}
,{"balance":"0","id":1623703,"price":184.26,"sid":1994214}
,{"balance":"0","id":1623704,"price":212.16,"sid":1993364}
,{"balance":"0","id":1623647,"price":418.48,"sid":1994638}
,{"balance":"0","id":1623645,"price":313.14,"sid":1993352}
,{"balance":"0","id":1623659,"price":418.48,"sid":1994640}
,{"balance":"0","id":1623686,"price":550.8,"sid":1995521}
,{"balance":"0","id":1623649,"price":155.4,"sid":1994204}
,{"balance":"0","id":1623643,"price":391.68,"sid":1995513}
,{"balance":"0","id":1623664,"price":155.4,"sid":1994207}
,{"balance":"0","id":1623622,"price":155.4,"sid":1994199}
,{"balance":"0","id":1623669,"price":155.4,"sid":1994208}
,{"balance":"0","id":1623635,"price":244.94,"sid":1993762}
,{"balance":"0","id":1623672,"price":244.94,"sid":1993768}
,{"balance":"0","id":1623651,"price":244.94,"sid":1993764}
,{"balance":"0","id":1623629,"price":313.14,"sid":1993350}
,{"balance":"0","id":1623677,"price":550.8,"sid":1995519}
,{"balance":"0","id":1623630,"price":244.94,"sid":1993761}
,{"balance":"0","id":1623616,"price":155.4,"sid":1994198}
,{"balance":"0","id":1623707,"price":184.26,"sid":1994215}
,{"balance":"0","id":1623617,"price":418.48,"sid":1994633}
,{"balance":"0","id":1623665,"price":418.48,"sid":1994641}
,{"balance":"0","id":1623619,"price":313.14,"sid":1993348}
,{"balance":"0","id":1623694,"price":212.16,"sid":1993362}
,{"balance":"0","id":1623692,"price":244.94,"sid":1993772}
,{"balance":"0","id":1623627,"price":391.68,"sid":1995510}
,{"balance":"0","id":1623679,"price":468.43,"sid":1994644}
,{"balance":"0","id":1623674,"price":155.4,"sid":1994209}
,{"balance":"0","id":1623621,"price":244.94,"sid":1993759}
,{"balance":"0","id":1623662,"price":212.16,"sid":1993355}
,{"balance":"0","id":1623653,"price":418.48,"sid":1994639}
,{"balance":"0","id":1623670,"price":418.48,"sid":1994642}
,{"balance":"0","id":1623699,"price":212.16,"sid":1993363}
,{"balance":"0","id":1623646,"price":244.94,"sid":1993763}
,{"balance":"0","id":1623681,"price":244.94,"sid":1993770}
,{"balance":"0","id":1623634,"price":155.4,"sid":1994201}
,{"balance":"0","id":1623683,"price":2.5761914952e+09,"sid":1993359}
,{"balance":"0","id":1623638,"price":134.31,"sid":1995070}
,{"balance":"0","id":1623697,"price":244.94,"sid":1993773}
,{"balance":"0","id":1623613,"price":134.31,"sid":1995066}
,{"balance":"0","id":1623658,"price":212.16,"sid":1993354}
,{"balance":"0","id":1623663,"price":391.68,"sid":1995516}
]

**Comment by jetexe** [comment]
Обратите внимание на цены.

**Comment by pahanini** [comment]
На данный товар неверно выставлена цена. Это не является программной ошибкой.
