### ISSUE TITLE
установка без  composer?

### ISSUE THREAD

**Issue by bigsylk** [sima-land/api-php-client#55]
Как можно выполнить установку без применения  composer?

**Comment by pastuhov** [comment]
а какая проблема в установке через composer?

**Comment by bigsylk** [comment]
Проблема в самой установки самого  composer

**Comment by pastuhov** [comment]
Боюсь, что без composer установка будет очень трудоемкой. Нужно скачать все зависимости согласно файлу https://github.com/sima-land/api-php-client/blob/master/composer.json. И зависимости зависимостей. 
Отказ от composer скорее всего не может являться решением.
