### ISSUE TITLE
Поиск товара по SID API v5

### ISSUE THREAD

**Issue by kikimor** [sima-land/api-php-client#57]
Не увидел в документации возможности поиска товара по SID, как можно было делать в API v.3:
`GET https://www.sima-land.ru/api/v3/item?sid=1125295`

Впрочем, не увидел возможности вообще как-либо фильтровать результаты. Планируется ли в API v.5 такое реализовывать?

**Comment by pahanini** [comment]
API v5 предполагает другую модель использования - быстро выкачать базу с товарами к себе на сайт. Реализация поиска и фильтров в этом случае предполагается на стороне клиента.
