### ISSUE TITLE
Ошибка в документации API v3, атрибут has_balance

### ISSUE THREAD

**Issue by kikimor** [sima-land/api-php-client#58]
В документации к методу https://www.sima-land.ru/api/v3/help/#Товар указано, что атрибут `has_balance` по умолчанию не предустановлен никаким значением, хотя по факту он установлен в значение 1, т.к. [без его указания](https://www.sima-land.ru/api/v3/item?sid=966850) удаленные товары не показываются.

**Comment by Gaus57** [comment]
Да, действительно в документации было не правильно указано значение по умолчанию для этого и нескольких других параметров. Ошибку исправили, изменения можно посмотреть в https://www.sima-land.ru/api/v3/help/#changelog. Спасибо!
