### ISSUE TITLE
Установка - Could not find package ~3 at any version for your minimum-stability 

### ISSUE THREAD

**Issue by 4seasonsu** [sima-land/api-php-client#59]
composer require "sima-land/api-php-client": "~3"

 [InvalidArgumentException]                                                                                                 
  Could not find package ~3 at any version for your minimum-stability (stable). Check the package spelling or your minimum-    stability

**Comment by pastuhov** [comment]
Подняли minimum-stability до stable, Ваша проблема должна решиться.
