### ISSUE TITLE
Проблема при установке при помощи composer

### ISSUE THREAD

**Issue by dimqakolyada** [sima-land/api-php-client#62]
При изучении документации по адресу https://www.sima-land.ru/api/v3/help/, узнал, что нужно ставить готовую библиотеку при помощи composer библиотеку для работы с API командой
`composer require "sima-land/api-php-client": "~3"`

Не получается установить библиотеку данной командой, выдает ошибку:
```
[InvalidArgumentException]
  Could not find a matching version of package ~3. Check the package spelling
  , your version constraint and that the package is available in a stability
  which matches your minimum-stability (stable).
```

**Comment by pastuhov** [comment]
Верное написание команды такое: `composer require "sima-land/api-php-client:~3"`

**Comment by dimqakolyada** [comment]
Снова ошибка после команды, теперь такая: 
 
Problem 1
    - The requested package sima-land/api-php-client No version set (parsed as 1.0.0) is satisfiable by sima-land/api-php-client[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.

**Comment by pastuhov** [comment]
Судя по ответу команды, версия указана неверно.
Скорее всего команда неверная.
