### ISSUE TITLE
Поведение has_balance 

### ISSUE THREAD

**Issue by kikimor** [sima-land/api-php-client#66]
Здравствуйте!

Пару дней назад изменилось поведение API v3, а именно поведение параметра has_balance.

Согласно документации:
has_balance - Показывать только товары, которые есть на складе
 
При значении 1 (которая установлено по умолчанию), возвращались только те товары, которые есть на складе. При значении 0 - возвращались товары без учета наличия.

В данный момент работает так:
has_balance == 0 - ищет товары, которых нет на складе
has_balance == 1 - ищет товары, которые есть на складе

Таким образом, пропала возможность находить товар по SID без учета наличия, приходится делать два запроса. 

Например, по запросу товар, который есть на складе, сейчас не возвращается -> https://www.sima-land.ru/api/v3/item/?sid=1552044&has_balance=0.

По возможности - поправьте, пожалуйста. Не удобно делать два запроса.

Спасибо!

**Comment by pastuhov** [comment]
День добрый!

Попробуйте передать пустой значение в has_balance
Пример: https://www.sima-land.ru/api/v3/item/?has_balance=

**Comment by kikimor** [comment]
Спасибо!
