### ISSUE TITLE
Отправка POST запроса

### ISSUE THREAD

**Issue by Brizhanev** [sima-land/api-php-client#71]
В сущностях, где требуется отправка GET запроса все работает, но для сущности delivery-price необходимо отправлять POST запрос, пробую так

$client = new \SimaLand\API\Rest\Client([
      'login' => 'XXX',
      'password' => 'XXX',
      'pathToken' => 'xxx/xxx',
      'baseUrl' => 'https://www.sima-land.ru/api/v3',
    ]);

    $request = new \SimaLand\API\Rest\Request([
      'method' => 'POST',
      'entity' => 'delivery-price',
      'postParams' => [
        'settlement_id' => 'XXX',
        'items' => json_encode([])
      ]
    ]);

    $responses = $client->batchQuery([$request]);

Приходит ответ, что параметры settlement_id и items не переданы. И еще вопрос, если в batchQuery передать очень много запросов, они будут отправлены с учетом лимита в 30 запросов в секунду?

**Comment by pastuhov** [comment]
#74
