### ISSUE TITLE
Получить данные товара не в наличии

### ISSUE THREAD

**Issue by denbor** [sima-land/api-php-client#75]
Предположим, есть товар с артикулом sima land 1521100. Этот товар сейчас не в наличии на sima-land.ru.

Требуется как-то получить по api данные этого товара. Пробовал без результата
https://www.sima-land.ru/api/v3/item/?sid=1521100
а также 
https://www.sima-land.ru/api/v3/item/?sid=1521100&is_disabled=1&is_deleted=1

Возможно ли в принципе получить через api данные товара не в наличии по sima артикулу?
Если да, то как это сделать?

**Comment by EvgenyGavrilov** [comment]
Здравствуйте!
Попробуйте добавить GET параметр has_balance=0
https://www.sima-land.ru/api/v3/item/?sid=1521100&has_balance=0

**Comment by denbor** [comment]
Спасибо! Это то что нужно.

**Comment by denbor** [comment]
Подскажите пожалуйста, что не так с этим товаром
https://www.sima-land.ru/1203169/igra-fanty-romanticheskie-dlya-dvoih-10-pervyh-svidaniy/

Не ищется по api по запросу 
https://www.sima-land.ru/api/v3/item/?sid=1203169
также его нет в таком варианте
https://www.sima-land.ru/api/v3/item/?sid=1203169&has_balance=0

**Comment by artezh** [comment]
А Вам есть 18 лет ?

**Comment by denbor** [comment]
Я понял, нужно добавлять параметр &with_adult=1

https://www.sima-land.ru/api/v3/item/?sid=1203169&with_adult=1
