### ISSUE TITLE
Как получить фото товара

### ISSUE THREAD

**Issue by denbor** [sima-land/api-php-client#76]
Предположим, что я получил ссылки на фото товара из
https://www.sima-land.ru/api/v3/item/?sid=1816492

```
<photos>
<item>
<url_part>
https://cdn2.static1-sima-land.com/items/1569976/0/
</url_part>
<version>0</version>
</item>
<item>
<url_part>
https://cdn2.static1-sima-land.com/items/1569976/1/
</url_part>
<version>0</version>
</item>
</photos>
```

Каким образом теперь получить фото из ссылок наподобие
https://cdn2.static1-sima-land.com/items/1569976/0/
?

Эти фото не открываются просто по ссылке, пишут 403 forbidden.
Попробовал получить через curl с авторизацией через логин и пароль на sima-land - без результата.
```
$saveto = DIR_IMAGE . 'f23134.jpg';
$ch = curl_init ($url);
curl_setopt($ch, CURLOPT_HEADER, 0);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_BINARYTRANSFER,1);
curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
curl_setopt($ch, CURLOPT_USERPWD, 'mylogin*:mypass*');
$raw=curl_exec($ch);
curl_close ($ch);
if(file_exists($saveto)){
  unlink($saveto);
}
$fp = fopen($saveto,'x');
fwrite($fp, $raw);
fclose($fp); 
```
Каким образом автоматически получить актуальные фото товара (который может быть не в наличии на sima-land) без водяных знаков sima-land?

**Comment by EvgenyGavrilov** [comment]
Здравствуйте!
Поле `photos` сущности `item` содержит список базовых URL для получения фотографий. Если к базовому URL добавть имя файла желаемого размера то получим полный URL фотографии.

Например, базовый URL `https://st-sima.r.worldssl.net/items/1277617/0/`, имя файла `700.jpg`, полный URL `https://st-sima.r.worldssl.net/items/1277617/0/700.jpg`

Список всех возможный имен файлов можно получить по API [https://www.sima-land.ru/api/v3/photo-size/](https://www.sima-land.ru/api/v3/photo-size/)

**Comment by denbor** [comment]
Спасибо! Проблема решена. В итоге, получаю по API ID товара по его артикулу, и подставляю этот id в этот URL:
https://cdn0.static1-sima-land.com/items/**1569976**/0/700-nw.jpg

Получаю фото товара без водяных знаков.
