### ISSUE TITLE
Всего 1 элемент в массиве 'modifier_items'.

### ISSUE THREAD

**Issue by bushaev-denis** [sima-land/api-php-client#78]
При expand\`e товара с modifier_items, в приложении php в массиве 'modifier_items'.

Лог запроса: `[2019-05-08 10:43:47] SimaParser.INFO: Send request https://www.sima-land.ru/api/v3/item/ {"getParams":{"with_adult":1,"expand":"modifier_items","id-greater-than":1340879,"id-mf":"5,4"},"postParams":null}` (это просто пример запроса, не конкретно товара в котором есть разновидность, но настройки такие).

Но при составлении запроса ч-з Postman, все нормально, в массиве оказываются все модификации товара.

**Comment by EvgenyGavrilov** [comment]
Здравствуйте!
В массиве modifier_items может быть 1 элемент в случаи когда у товара может быть одна модификация, сам товар.

Можете привести конкретный пример когда api парсер не верно возвращает данные?

**Comment by bushaev-denis** [comment]
Вот, пример товара:
api-php-client (обычный var_dump с предварительной чисткой ненужных для скрина элементов массива): http://prntscr.com/nlvbel
Postman (видно в элементе массива modifier_items скрытые дочерние элементы в кол-ве 5 штук): http://prntscr.com/nlv9aa

Дистр качался с репы по composer, никак не модифицировался.
Инициализация Клиента: http://prntscr.com/nlvgx0
Тестовый код парсинга товаров: http://prntscr.com/nlvh61

**Comment by EvgenyGavrilov** [comment]
Ошибка на стороне сайта, завели задачу по исправлению. Как только ошибка будет исправлена, отпишусь.

Спасибо за сообщение.

**Comment by bushaev-denis** [comment]
Как там успехи?

**Comment by artezh** [comment]
Добрый день!
Извиняюсь за долгий ответ. В целях оптимизации производительности было принято решение отказаться от вывода всех модификаторов товара  в листинге.
Для того, чтоб получить данную функциональность у себя, Вы можете сгруппировать результаты парсинга по полю parent_item_id, тем самым получив группы модификаторов
