### ISSUE TITLE
Не могу установить вашу библиотеку

### ISSUE THREAD

**Issue by inmtoo** [sima-land/api-php-client#80]
Приветствую,

Ставлю библиотеку, меня сопровождает это:
![image](https://user-images.githubusercontent.com/46413500/71251936-a911a980-2334-11ea-8472-312195d8cfce.png)

Использовать планирую в Laravel, соответственно, Laravel не видит данные классы. Подскажите, пожалуйста, как мне всё же поставить Ваше решение и использовать в Laravel?

**Comment by Lysenkov8** [comment]
Добрый день 

Подобная проблема есть в #84 
Разработчикам передали информацию, займутся в ближайшее время

**Comment by Lysenkov8** [comment]
Добрый день, был выложен новый релиз, который должен решить вашу проблему
