### ISSUE TITLE
фильтр по товарам партнеров.

### ISSUE THREAD

**Issue by phrakon** [sima-land/api-php-client#81]
Здравствуйте. На сайте есть товары партнеров:
http://skrinshoter.ru/s/100320/T1uSr9n4

Какой атрибут отвечает за это или можно ли их каким-то образом исключить из выдачи?

**Comment by Lysenkov8** [comment]
Добрый день,

При запросе данных по товару (GET https://www.sima-land.ru/api/v3/item/) есть параметр
is_remote_store. 
Где 0 - Показывать только наши товары, 1 - Показывать только товары партнеров
