### ISSUE TITLE
Где взять параметр?

### ISSUE THREAD

**Issue by alesheyk** [sima-land/api-php-client#82]
Доброго дня. Где брать первый параметр для авторизации: 'oauth_source_id' => '<OAUTH_SOURCE_ID>'?

![image](https://user-images.githubusercontent.com/25950011/101353540-d092b680-38a4-11eb-9242-faf250de5705.png)

**Comment by EvgenyGavrilov** [comment]
Здравствуйте. С какой целью вы хотите использовать этот endpoint в API?

**Comment by alesheyk** [comment]
пытался разобраться в API, чтобы подгрузить текущую корзину Совместной покупки, если это конечно возможно, но не до конца разобрался с авторизацией

> Здравствуйте. С какой целью вы хотите использовать этот endpoint в API?

**Comment by EvgenyGavrilov** [comment]
Для аутентификации можно воспользоваться HTTP Basic Auth. Опционально можно авторизоваться через HTTP Bearer Auth, используя JWT. Получение JWT смотрите в [соответствующем разделе](https://www.sima-land.ru/api/v3/help/#%D0%9F%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-jwt)
