### ISSUE TITLE
Просьба обновить зависимости guzzle и monolog

### ISSUE THREAD

**Issue by NavigatorZero** [sima-land/api-php-client#84]
Хочу интегрировать вашу библиотеку в свой проект на laravel, но зависимости не совместимы, 7 версия просит monolog 2, 8 guzzle ~7 и monolog 2

**Comment by Lysenkov8** [comment]
Добрый день

Разработчикам информацию передали, в ближайшее время постараются взять в работу

**Comment by Lysenkov8** [comment]
Добрый день, был выложен релиз в котором обновили зависимости
