### ISSUE TITLE
Ошибка авторизации

### ISSUE THREAD

**Issue by ElectroMyStyle** [sima-land/api-php-client#86]
Здравствуйте, не могу авторизоваться с валидным логином (e-mail) и паролем.
Ни с помощью вашей [библиотеки](https://github.com/sima-land/api-php-client), ни с помощью Postman авторизация не проходит.
![image](https://user-images.githubusercontent.com/5159210/176399306-0212ed74-9a21-4bc7-b3bd-d35c16f3b4be.png)

Через cURL тоже не работает:
```
$curl = curl_init('https://www.sima-land.ru/api/v3/auth/');
curl_setopt($curl, CURLOPT_HTTPHEADER, array('Accept: application/json'));
curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
curl_setopt($curl, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
curl_setopt($curl, CURLOPT_USERPWD, '<LOGIN>:<PASSWORD>');
$json = curl_exec($curl);
curl_close($curl);
```

До вчерашнего дня (28.06.2022) всё работало отлично, скрипт клиента работал последние пол года без нареканий. То есть просроченные токены удалялись и возобновлялись с помощью авторизации (судя по логике библиотеки).
Авторизация больше не будет работать или это ошибка на сервере?

**Comment by Lysenkov8** [comment]
Добрый день 

Информацию передали разработчикам, так же в ближайшее время планируется добавление функционала получение JWT токена в Личном кабинете со сроком действия 1 год.

**Comment by ElectroMyStyle** [comment]
Добрый день. Хорошо, спасибо, будем ждать исправления авторизации

**Comment by Lysenkov8** [comment]
Добрый день

От разработчиков поступила обратная связь.

На данный момент Basic авторизация доступна для ограниченного списка учетных записей. 
Получение JWT всё также доступно любому авторизованному на сайте пользователю, путем выполнения запроса к /api/v3/auth/
